module.exports = {
    ABS_URL: "https://www.hirist.com",
    DOMAIN_NAME: ".hirist.com",
    LOGO: "hirist",
    INC_HOST: "HIRIST",
    META_TITLE: "IT",
    FAVICON_LINK: "https://static.hirist.com/resources/img/hirist/favicon.ico",
    //JOBSEEK_SERVICE_URL: "https://jobseeker-api.hirist.com",
    JOBSEEK_SERVICE_URL: "https://stagenodenew.hirist.com",
    //JOBSEEK_SERVICE_URL: "http://localhost:3002",
    LEARNING_SERVICE_URL: "https://learnngrow-api.hirist.com",
    //USER_SERVICE_URL: "https://user-api.hirist.com",
    USER_SERVICE_URL: "https://stagejobusernew.hirist.com",
    //USER_SERVICE_URL: "http://localhost:3003",
    COMPANY_SERVICE_URL: "https://company-api.hirist.com",
    AD_SERVICE_URL: "https://billboard.iimjobs.com",
    ANGEL_SERVICE_URL: "https://angel.hirist.com",
    RECRUITER_SERVICE_URL: "https://api-rec.hirist.com",
    LEARNGROW_SERVICE_URL: "https://learngrowapi.hirist.com",
    BIDDER_SERVICE_URL: "https://bidder.hirist.com",
    LEARNING_URL: "https://learning.hirist.com",
    SHOWCASE_URL: "https://showcase.hirist.com",
    STATIC_IMG_URL: "https://static.hirist.com",
    EDGAR_IMG_URL: "https://edgar.hirist.com",
    MAVEN_URL: "https://maven.hirist.com",
    CHAT_BUNDLE_URL: "https://recruiter-hirist-static-content.s3.ap-south-1.amazonaws.com/Chat/Production/Jobseeker/v2/my-chat/bundle.min.js",
    STICKY_CHAT_BUNDLE_URL: "https://recruiter-hirist-static-content.s3.ap-south-1.amazonaws.com/Chat/Production/Jobseeker/v2/sticky-chat/bundle.min.js",
    VIDEO_CHAT_BUNDLE_URL: "https://recruiter-hirist-static-content.s3.ap-south-1.amazonaws.com/Chat/Production/Jobseeker/v2/video-chat/bundle.min.js",
    SCREENING_RESPONSE_URL: "https://s3.ap-south-1.amazonaws.com/assessment-hirist-media/sdk/screening/job-seeker-response/js/assessment.min.js",
    SCREENING_URL: "https://s3.ap-south-1.amazonaws.com/assessment-hirist-media/sdk/screening/job-seeker-question/js/assessment.min.js",
    ASSESSMENT_URL: "https://assessment-hirist-media.s3.ap-south-1.amazonaws.com/sdk/assessment/jobseeker/v2/js/assessment-job-seeker.min.js",
    BROWSER_NOTIFICATION_URL: "https://webnotification.iimjobs.com/js/iimjobs-push-notification-qa.js",
    
    COOKIE: "HIRIST_CK1",
    showMaven: 0,
    showRecommendedJobs: 0,
    showBlogs: 0,
    showTags: 1,
    selfAssessment: 0,
    production: 1,
    seeker_enc: "hirist_seeker_enc",
    s3Url: 'https://staticlogo.hirist.com',
    proUser: 0,
    PLAYSTORE_URL: "https://bit.ly/hiristapp_android",
    APPSTORE_URL: "https://bit.ly/hiristapp_iOS",
    RESUME_UPLOAD_URL : 'https://vinci.hirist.com/',
    authToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaXQudmVybWFAaWltam9icy5jb20iLCJpYXQiOjE1Njk0MTgwNDAsImV4cCI6MTU2OTUwNDQ0MH0.W7x1yeSx1QkKFOxyHGytuKGjCCLTV-uyrcysDAwyB5s',
    R_TOKEN: 'R_TOKEN_HIRIST',
    BROWSER_NOTIFICATION_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNjIyMCIsInR5cGUiOjIsImNyZWF0ZWRUaW1lIjoxNjI5MjAyMTIwOTg4LCJpYXQiOjE2MjkyMDIxMjAsImV4cCI6MTY2MDczODEyMH0.upOfr5uG7plwjETvFlZgbpoZgCpiuec3sCNd26bHH0Y',
  }
  
  